### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method outlinedTextFieldColors-M37tBTI(JJJJJJJJLandroidx/compose/foundation/text/selection/TextSelectionColors;

### ISSUE THREAD

**Issue by santanaleonardo** [TuleSimon/xMaterialccp#19]
When I update the libraries above to the last version the error occurs.

from : androidx.compose:compose-bom:2024.08.00
to: androidx.compose:compose-bom:2024.10.00

from : androidx.compose.material3:material3-window-size-class:1.2.1
to: androidx.compose.material3:material3-window-size-class:1.3.0

 MaterialCountryCodePicker(pickedCountry = { phone ->
                                accountViewModel.setCountryCode(phone.countryCode)
                                accountViewModel.setCountryPhoneCode(phone.countryPhoneCode)
                            },
                                defaultCountry = getLibCountries().single { it.countryCode == defaultLang },
                                error = !isValidPhone,
                                text = phoneNumber,
                                onValueChange = { accountViewModel.setPhoneNumber(it) },
                                searchFieldPlaceHolderTextStyle = MaterialTheme.typography.bodyMedium,
                                searchFieldTextStyle = MaterialTheme.typography.bodyMedium,
                                phonenumbertextstyle = MaterialTheme.typography.bodyMedium,
                                countrytextstyle = MaterialTheme.typography.bodyMedium,
                                countrycodetextstyle = MaterialTheme.typography.bodyMedium,
                                showErrorText = true,
                                showCountryCodeInDIalog = true,
                                showDropDownAfterFlag = true,
                                textFieldShapeCornerRadiusInPercentage = 10,
                                searchFieldShapeCornerRadiusInPercentage = 10,
                                appbartitleStyle = MaterialTheme.typography.titleLarge,
                                countryItemBgShape = RoundedCornerShape(5.dp),
                                showCountryFlag = true,
                                showCountryCode = true,
                                isEnabled = true,
                                colors = ccpDefaultColors(
                                    primaryColor = MaterialTheme.colorScheme.primary,
                                    errorColor = MaterialTheme.colorScheme.error,
                                    backgroundColor = MaterialTheme.colorScheme.background,
                                    surfaceColor = MaterialTheme.colorScheme.surface,
                                    outlineColor = MaterialTheme.colorScheme.outline,
                                    disabledOutlineColor = MaterialTheme.colorScheme.outline.copy(
                                        0.1f
                                    ),
                                    unfocusedOutlineColor = MaterialTheme.colorScheme.onBackground.copy(
                                        0.3f
                                    ),
                                    textColor = MaterialTheme.colorScheme.onBackground.copy(
                                        0.7f
                                    ),
                                    cursorColor = MaterialTheme.colorScheme.primary,
                                    topAppBarColor = MaterialTheme.colorScheme.surface,
                                    countryItemBgColor = MaterialTheme.colorScheme.surface,
                                    searchFieldBgColor = MaterialTheme.colorScheme.surface,
                                    dialogNavIconColor = MaterialTheme.colorScheme.onBackground.copy(
                                        0.7f
                                    ),
                                    dropDownIconTint = MaterialTheme.colorScheme.onBackground.copy(
                                        0.7f
                                    )

                                )
                            )

 Process: br.com.b8.raffle, PID: 31863
                            java.lang.NoSuchMethodError: No virtual method outlinedTextFieldColors-M37tBTI(JJJJJJJJLandroidx/compose/foundation/text/selection/TextSelectionColors;JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJLandroidx/compose/runtime/Composer;IIIIIII)Landroidx/compose/material3/TextFieldColors; in class Landroidx/compose/material3/TextFieldDefaults; or its super classes (declaration of 'androidx.compose.material3.TextFieldDefaults' appears in /data/app/~~LbNlmYQ43cNaQp-WKWW6cQ==/br.com.b8.raffle-7itvGKcIUaEMSKoFDYfjqQ==/base.apk!classes13.dex)
                            	at com.simon.xmaterialccp.component.MaterialCountryCodePickerKt.MaterialCountryCodePicker-EcZREWE(MaterialCountryCodePicker.kt:145)
                            	at br.com.b8.raffle.ui.account.AccountScreenKt$AccountScreen$7$2.invoke(AccountScreen.kt:322)
                            	at br.com.b8.raffle.ui.account.AccountScreenKt$AccountScreen$7$2.invoke(AccountScreen.kt:217)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:118)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                            	at androidx.compose.material3.ModalBottomSheetKt$ModalBottomSheetContent$7.invoke(ModalBottomSheet.kt:341)
                            	at androidx.compose.material3.ModalBottomSheetKt$ModalBottomSheetContent$7.invoke(ModalBottomSheet.kt:289)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                            	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:126)
                            	at androidx.compose.material3.SurfaceKt$Surface$1.invoke(Surface.kt:108)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                            	at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s(Surface.kt:105)
                            	at androidx.compose.material3.ModalBottomSheetKt.ModalBottomSheetContent-IQkwcL4(ModalBottomSheet.kt:218)
                            	at androidx.compose.material3.ModalBottomSheetKt$ModalBottomSheet$3.invoke(ModalBottomSheet.kt:175)
                            	at androidx.compose.material3.ModalBottomSheetKt$ModalBottomSheet$3.invoke(ModalBottomSheet.kt:168)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                            	at androidx.compose.material3.ModalBottomSheet_androidKt$ModalBottomSheetDialog$dialog$1$1$1.invoke(ModalBottomSheet.android.kt:300)
                            	at androidx.compose.material3.ModalBottomSheet_androidKt$ModalBottomSheetDialog$dialog$1$1$1.invoke(ModalBottomSheet.android.kt:296)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                            	at androidx.compose.material3.ModalBottomSheetDialogLayout.Content(ModalBottomSheet.android.kt:354)
                            	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:259)
                            	at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:258)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                            	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:216)
                            	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:132)
                            	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:131)
                         E  	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
                            	at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:121)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:155)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:154)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                            	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:154)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:133)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                            	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                            	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:97)
                            	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3595)
                            	at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3522)
                            	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:743)
                            	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1122)
                            	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3876)
                            	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3876)
                            	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3876)
                            	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:649)
                            	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:635)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                            	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1626)
                            	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:124)
                            	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:180)
                            	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
                            	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                            	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
                            	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1707)
                            	at android.view.View.dispatchAttachedToWindow(View.java:22479)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3686)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                            	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3695)
                            	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3669)
                            	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
                            	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
                            	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
                            	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
                         E  	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
                            	at android.view.Choreographer.doFrame(Choreographer.java:852)
                            	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
                            	at android.os.Handler.handleCallback(Handler.java:942)
                            	at android.os.Handler.dispatchMessage(Handler.java:99)
                            	at android.os.Looper.loopOnce(Looper.java:226)
                            	at android.os.Looper.loop(Looper.java:313)
                            	at android.app.ActivityThread.main(ActivityThread.java:8762)
                            	at java.lang.reflect.Method.invoke(Native Method)
                            	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                            	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by santanaleonardo** [comment]
Hello, any news about this problem?

**Comment by TuleSimon** [comment]
what version are u using and whats your compose bom version?

**Comment by santanaleonardo** [comment]
I am using 2.13 version and new compose bom 2024.11.00
Both latest versions

**Comment by TuleSimon** [comment]
@santanaleonardo new version available v2.14 try it

**Comment by santanaleonardo** [comment]
@TuleSimon Now it's ok, thanks
